from typing import *


T = TypeVar("T", bound=Hashable)


class CycleError(ValueError):
    pass


class TopologicalSorter(Generic[T]):
    def __init__(self, graph: Optional[Mapping[T, Iterable[T]]]) -> None: ...
    def get_ready(self) -> Tuple[T, ...]: ...
    def add(self, node: T, predecessors: Tuple[T, ...]) -> None: ...
    def done(self, nodes: Tuple[T, ...]) -> None: ...
    def is_active(self) -> bool: ...
    def remove(self, nodes: Tuple[T, ...]) -> None: ...
    def prepare(self) -> None: ...
    def static_order(self) -> Iterable[Tuple[T, ...]]: ...
